#!/bin/bash

# Retrieve arguments
domain=$1
path=$2

sudo yunohost app checkurl $domain$path -a plexmediaserver
if [[ ! $? -eq 0 ]]; then
  exit 1
fi

# Check port availability
sudo yunohost app checkport 32400
if [[ ! $? -eq 0 ]]; then
  exit 1
fi

# Remove trailing "/" for next commands
path=${path%/}

# Open port in firewall
sudo yunohost firewall allow TCP 32400 > /dev/null 2>&1

# Install plex
sudo sh -c 'echo "deb http://shell.ninthgate.se/packages/debian strech main" >> /etc/apt/sources.list.d/plexmediaserver.list'
sudo curl http://shell.ninthgate.se/packages/shell-ninthgate-se-keyring.key | sudo apt-key add -
sudo apt-get update
sudo apt-get install -y plexmediaserver

//locate plex files in /home/yunoshost.app/plexmediaserver
sudo service plexmediaserver stop
sudo ln -s /var/lib/plexmediaserver /home/yunohost.app/plexmediaserver 
sudo service plexmediaserver start

# enable auto start
sudo chmod +x /etc/init.d/plexmediaserver
sudo update-rc.d plexmediaserver defaults

# Monitor service
sudo yunohost service add plexmediaserver

# Disable SSO 
sudo yunohost app setting plexmediaserver skipped_uris -v "/"


# Configure Nginx and generate SSOwat conf
sudo sed -i "s@PATHTOCHANGE@$path@g" ../conf/nginx.conf
sudo cp ../conf/nginx.conf /etc/nginx/conf.d/$domain.d/plexmediaserver.conf
sudo service nginx reload
sudo chown root: $nginxconf
sudo chmod 600 $nginxconf
echo $?
sudo yunohost app ssowatconf
