#!/bin/bash

domain=$(sudo yunohost app setting plexmediaserver domain)

sudo yunohost firewall disallow TCP 32400

sudo yunohost service remove plexmediaserver

sudo rm /etc/nginx/conf.d/$domain.d/plexmediaserver.conf

sudo service plexmediaserver stop
sudo apt-get remove -y plexmediaserver
sudo apt-get -y autoremove

sudo service nginx reload
sudo yunohost app ssowatconf
